CREATE TABLE IF NOT EXISTS bot(id INTEGER PRIMARY KEY NOT NULL);

CREATE TABLE IF NOT EXISTS guild(id INTEGER PRIMARY KEY NOT NULL);

CREATE TABLE IF NOT EXISTS guild_bot(
    bot_id INTEGER,
    guild_id INTEGER,
    FOREIGN KEY(bot_id) REFERENCES bot(id) ON DELETE CASCADE,
    FOREIGN KEY(guild_id) REFERENCES guild(id) ON DELETE CASCADE
);